'''
This is a short script that takes an input string and returns a count of A, C, G & T.

'''

dna_string = "TCCCGCGTTACGGCCAGTCGGGTCCGTGGGGTAGGTGACTGCGTTCGTTGATGCACACTGGCGCGTAATTAACGACTGTTAGTAAAGAGCCTGCATGGACACGATCTGACGTCCATTAACGGTGTGTGACTACCGTGAAAACAGTCATCTTCGGGAGAGGACCGAGTAAAGCTGTTCGTACCAGTCTATCCCTCTGCCAAGCGGGTCACACGATAGCTCGGCGGCATATGTAAAGCACGGTTAGGACCTCGCATATCCTGCCCGTTGCGAACGAAACGTGACGAGCCGACGCCCCGGAGCTACTCAGTCGAATCACACAGGCTGTACCCGCTCTCGTGAATATCAGCCCTCGGGCCGGCTAACGTCTCCGTTCAGGCGCGGTATGTGTTGTGTGCAAACACTTTTAATGGTATTCCTCCTCACCACTGTGCTTGCATTTTTATTGATCTATCAGTTAACTATCCCCGGCGCTTTCTTTCCCAGACAGTTTGTGGTGCAAAGTGAGCTACTGTCTAACACAAATGGCACGCAACCCCTATATATCACGTCCAGCGTAAGTGAGGTCACCTGTGGTGTTAGACAAGACTCCTGGAATGGGACACGTGTTTATCGTGCTTCTCAACCGCTGTTAACCCACCCTAGCGCGCGTAAGCGTAAGCTGGTGGCAGCTGGTAGCCCCTTAGCGTAGCTTCCATCGTAATGCCCGCACGAAAGACGACATATCAGAAACATGTAAAGAATCGGCGGTCTGTCAATCCGAGCTCTATGAGCGCAATTGCAAAAGTACGATTCAGGCAGTCTGCCCGAATGAAACCACTTAAGCCTACGAATGTCC"

def dna_counter(dna_string):
    """
    Takes an input sequence of DNA, converts it into a list and then counts the 
    
    Input Parameters: 
    dna_string is the DNA sequence that you want to check

    Output Parameters:
    A, C, G, T counts (also printed to console)
    """
    dna_lst = list(dna_string)
    A = 0
    C = 0
    G = 0
    T = 0
    for i in dna_lst:
        if i == "A":
            A = A + 1
        elif i == "C":
            C = C + 1
        elif i == "G":
            G = G + 1
        else:
            T = T + 1
    print (A, C, G, T)
    return A, C, G, T

dna_counter(dna_string)