def rna_to_protein(rna):
    '''
    Takes a string and returns a protein sequence WIHOUT 
    using biopython

    Input params:
    rna = rna string

    Output params:
    protein = protein sequence
    '''
    codon = []
    protein = []
    
    while rna:
        codon.append(rna[:3])
        rna = rna[3:]

    for triplet in codon:
        if triplet == 'AUG':
            protein.append('M')
        elif triplet == 'GCC' or triplet == 'GCG' or triplet == 'GCU' or triplet == 'GCA':
            protein.append('A')
        elif triplet == 'UUU' or triplet == 'UUC':
            protein.append('F')
        elif triplet == 'UUA' or triplet == 'UUG':
            protein.append('L')
        elif triplet == 'UCU' or triplet == 'UCC' or triplet == 'UCA' or triplet == 'UCG':
            protein.append('S')
        elif triplet == 'UAU' or triplet == 'UAC':
            protein.append('Y')
        elif triplet == 'UAA' or triplet == 'UGA':
            break #stop codon
        elif triplet == 'UGU' or triplet == 'UGC':
            protein.append('C')
        elif triplet == 'UGG':
            protein.append('W')
        elif triplet == 'CUU' or triplet == 'CUC' or triplet == 'CUA' or triplet == 'CUG':
            protein.append('L')
        elif triplet == 'CCU' or triplet == 'CCC' or triplet == 'CCA' or triplet == 'CCG':
            protein.append('P')
        elif triplet == 'CAU' or triplet == 'CAC':
            protein.append('H')
        elif triplet == 'CAA' or triplet == 'CAG':
            protein.append('Q')
        elif triplet == 'CGU' or triplet == 'CGC' or triplet == 'CGA' or triplet == 'CGG':
            protein.append('R')
        elif triplet == 'AUU' or triplet == 'AUC' or triplet == 'AUA':
            protein.append('I')
        elif triplet == 'ACU' or triplet == 'ACC' or triplet == 'ACA' or triplet == 'ACG':
            protein.append('T')
        elif triplet == 'AAU' or triplet == 'AAC':
            protein.append('N')
        elif triplet == 'AAA' or triplet == 'AAG':
            protein.append('K')
        elif triplet == 'AGU' or triplet == 'AGC':
            protein.append('S')
        elif triplet == 'AGA' or triplet == 'AGG':
            protein.append('R')
        elif triplet == 'GUU' or triplet == 'GUC' or triplet == 'GUA' or triplet == 'GUG':
            protein.append('V')
        elif triplet == 'GAU' or triplet == 'GAC':
            protein.append('D')
        elif triplet == 'GAA' or triplet == 'GAG':
            protein.append('E')
        elif triplet == 'GGU' or triplet == 'GGC' or triplet == 'GGA' or triplet == 'GGG':
            protein.append('G')
        
    protein = ''.join(protein)
    return protein

rna = 'AUGAGUUGCCCGACCCUCCGUAUCUCAAAAAUUUUUGUACGAUCAACAUACAAAAAUCCUGCCAUUAACAUCUGGAUGCGCAGCUUUGCCUUAUGUGGAAGGUAUCGGGAGGCACAGGAUCUGUCUGAGGGAAGAAGGGAUUUAAACCUAUGUGCCAUUUCGUUUGGUAACAUUCCGUUCGGACCGUUGCGCUUAUCAACGUGCGUACUCACACCAAACAAAUCCAUACCUCUGAUAGUAAGCCUCAAUUAUCGCCAUCUCGUAUGUUCAGGCUUCGUGUCAGUCUGUUGGAUUUGCGUGAUUGUACUAUCUCCACCCCGCCGGAAUGUUCAAAGCCUCCAAUACGAACAUAAACUCCGAUGCGUUACAAACUACCGACAAGGCCCAUCCGAGUCAUGGAUCCUAAUACACGUAAUUAGUGGUAACGCCGGAAAGCUUCGUAGGGAGUACUUCAACACUCGAGAAGCGCUCUUUCCUAUAUCCUGUCAGUCAGAUGGCGGCCGGCGAACUAGUCUAAUGGUGGACGUUUGUGUAAUAUCCUAUACUUGGAACUUCUUCACUAUUCAUGGGCCCCUUCUAUUAGGCGGUAGCGUUUACAAGUUAUGGCCUGUCGUCGAGUCCUUGCCGUCCAGUUUAUCUGAUAACCUUCGGCCGUACCAGGUGAAGGGGGUCCUUCUCUCCUUUUGUAGGAUUUCCCCUUCAUUGUGCGCGGGACUAUUUAGCCCACGCAAGGGAUUGCAUUAUUCUGAGGCGUCUAGUGCUAGACAAUCGUCUGUCGCACCGUACGCUGGGGGUUUAACUACUCGAACCCGAGCCUUAACUGGGUGCCAGAGCAUACUCCAACGCGAAGAGGGUAGCGUGCGAAUAAAAAUCCUUCCUACUAGCGACACGCUUAUCCAUGAUGGGAAGAGCCGAACGCCCCAGCACGGAGAUCCCUCACCGACAGUGACAUGGCUUGAUCUGUUACGUAUUACUUUCAUCCUACCCAUGCGCGGACAUGUCGAGGGCCGACAGAAUAACUUGUCCAUGAUGUCGCUUUCGUGCGGGGUGUGGCUCGGGGCAGAAGCGUCCUUACCGGGACAGGUACUAUUUAUAUAUGGAUCAUCGUCUAAGAUUUCACCCUCGUACAAAGCGGAGGCCAGACCGCAUAGUCGACGUUGCGGAAUGCCUCCUGACGACGUCUAUCACGGUACUGCUUCGUUGGAUGGUGAGGGCCUCGCAUUUGCGUGCUUACCAGGGCUGAUUUCAUUCAGGCCUGGUACCGACGAAAGAUAUCAUCGUGAGUCUAUGACCCGCGCCUUCGAGGAAUGCUGUGCUUAUGACCCACGACUAGUUGUCACGCUACAGCAAGGGCCGCAGCGCUGUAGGUACGCAUAUAUUCUCCGGAAACCAUCACAAAGUCUCCGCCCCGCUGCCGAUGUGAACGACACUAACAAAGAACUUUCAGAUCCGUGCGUUCCGCUACUAACAUUCCGAUCCUGUAUGGGUUUCUGCUUGCGUCGAAUCACAACGACGAUAAGGGCCAAUCCUUCUAAAGUGACCGGGCACGUGAUAUUACAUCUGGGUGUUCUGGCGGCUAAGGACAAUGCCGGCGCAUUGGAAUACCGUACCGGGUCUCUUGGAGUCCAAUACGCCUGGGCUCAUUACCAUCAUCGAACUUACGUCUACUCCCAUGCAACCACGGGAUUAGAUACAAAGGGGUCCUACUCCCGCCGUUCCGAGAUCUGUCAAAUAAAGCAGUUUCGCGACACGUCGCAUGAUGGCGUAUGCGAUUACUUGUAUUUUGAAAAUACGCUUGCUCGAACGAGUGUGCCCCAAAUAAUACAUAUCGCUUUAUCAAACUUCACCGAGUACGGAUGCGUAGGACGAUCGCUUCGUGCCCAGUCAAGGUACAUCUACCCGGAUGGCGUACUAUACCGCGAAGGUAGAGGUAGGAGUUUAGCCAUUUUGGCUCGGGGGUGUGCGCUUGAAUUACACCGUGGGUCUCUGCGUGGGAACUCUGGCGCUAACACUAGGCUCGCUGGGCUUGGCAUAGCCGACCAUAGGUCUCAACGACGAUGCCUUUACGGCAUUGAAAGUCUGGUGGUGGUAGUGUCUAAAGGUCGAUUGGUAUGUCACUGGAUGAACGUUCCACAUCUCACUCCCCUAUACGCAUAUGCUACAAUAGAGCAUAACUCUUUCGGCCAAGUCUGUGGCGAAUUCCGAGGCAUGACCCCACUGCAGUCGGCAAUACAAGCCGAGCAAGAUUGGGUUUUUGCAUCUGAAGUCUUCGUUGGCACGACCGGCAUACAUCAGCAUCAGGCACAGGACUCGCAAUUUUUGCGGGCAGUUAUGUGUACACCAGUUCUAUCUGGCGCCGGUAGUCUUCAAAAUCUUGGCCUGCUUCGAAUUGCAAAGCUAUGGGGCUUUUCGUAUACAGCCCUUAAAGCCUGGUACCUCGUACGAUGGCGCAGGUUACUCCGAUUUCCAUCAAAAAAUAGGACCGCGGCACACCAUGUAGCAGGUCGGAAUGCCUUGGUCUGUAGAUCCGGAAUUGCUACCCCUUACGCGCGGUUUAGCGGCGCCCCAAACGGGGGCAGCAUUUCAGUCUCAUCUUCCGUUAGUGUUUUCCACACGCCCGGCAAGCUAAGGCCCGAACUGCACGCUCGCCCGACCCUUGCGCCCAAAGCGACGAGACAAGACAAACUCAACAGGACGAGCUGCAUUGUCGGGCGCAUCUACGCCUGCAGCAUGAUUAAUCGCCAUAAGCCCAUGAAGCAACCUUUGGGCACAUCUGCCGCCUGGGUUCUGCGUCAAACGCCGUUGACAUGUUGUUCUGGAGAAUCUAACGAGCCUAUCGUAAACGUACGCAUAGGUCAGGAUGAUGCGGUGGAAUCCCUCAAAUCCAAGGAGUGCCCUCCAUAUCUAACCUAUAAAGUCCAUGCCAGGCUGAGCGCAUACGUCAAGCGAUUCUGCCAUCGGCACACAGGCCCAUAUGCCUCAGCUGAUAGUGAACCUGAUGCGGACGCCGAUUUAGGUUUACGUUCACUUGUCCCUCAGCAAGAGACGAGUGAUGCUUCGCUAAAAGGGCGGCACCAGGGCUACAUCUUUCAUAUCAGAGAAGUAACGUUUUGUGCGAUUCGUGUCGAGUUUCCAUUUGGUGGUGACUGUCGAGUCUGUCCCUGUGGUUCACCUGGACCCUUAGCAACGGAGAUUGUAUUCCUAGCCUGGACCGGCCCCCAGCUACAUCUUGAUCGCAUAUCAACCCCCUAUAUAGUCGGGGGUUUCUUUAAACGGGGACCGCUUCCUACAGCCACUUCUUUUAAACGUCACACGCAGGAAGAGGCAGCCUUUUCGUCCCUGUCCGAACGCCAAGUGCAAGGUCUUGCACAUCCACGAGGAGGCUAUAGUUGCUCGAUACUUGAAAAAUAUGCAACGCAACAUUCGUCCGAAGUACACCAAGGUAGUCGAGUCAACGCCCGACGAGUUCUUUGGACUUCCAUUACAUUUACGGAGCAGGUGCAAGCGACUACGGUUUUGGGCCGAUUUCAUUCUAGUCGCCUUCGGUCCGUCCCUUGUACGGUCGGGGCUCAGAUCAGCCUGUAUUGUUCUAAAAGUACUAGUAUAAGGACUAGACCUCUGCUGUCCGUUGAUCUGGUAAAUUGCCGUGCGAAUUUGCUUGCAGCGUCAAGAAACAUCGGGACGGAGUUAUUGGAUGAAUGGCAUCAGGAUGCAGGGACAAACGGGCCUCUCGGCUGCUCGUAUUUAGCGUGCCUCGCUGGAAUAUGUCUAAUUACGUGUACAACGCACCUAAACCACGCUGCGCACGGACAACAUCUUUUACUCCCGCUGGCCGGGUCUACGUCGCCGGUCCUUGACAGGGGGGAUCUAUGCCCGGGCGAUUCGGCUCUUCGUCGGACUGGACAGGGGAAAGCAUAUUCUAGAUUUGAGGUUUUCAGUCAGCGGAUGUGUUUUUCAAUACCGCGGAAGGUCAGCCAUACACUCCAGAUCCCGGGCACGCUGCUAAUCUAUCAAGGGGGACUGAUUUUAUACUGCCGGACCCAUUGUAUCACUUUUUCAAGCAGCGACGUGGCCCGUGCUGUUACCGCACUCGCACAAAGCUCGCGUAUUCGGAGACGUUCGGACCCUCACCUGGGAGCACGGAACCGCCGCGAAGCGAGCGUGGAUGACCGUGCGCUACUCCUGCGUCAACGUUGGUGGGAUAUCCCACCGAUACCAGAGUCUUCUGUAUCCACCACGACUAUGUUCGCGCACCCCUACUUGAGGAGACGACUUGCACAAGGUUGGGAAAACAUAAUCCAGCCUCGUCAACUUGUCGCCAACUUCGCGAUUUUGCACUUUCGCGCAACCCCCCAAAGUGUACCUGGAGAAACCAACAAAAGUGGUGUAGCCGUCAGAAAUGUGAGGGGGGUCCGGUUUUAUGCAAGGUUGAGAGUAGGCGAGGUACAUGGUGCCACGGGGAGGCUCGAAGCCUGGCCGUCCUUGGAGAUCACUGGGCUGCUGGAUACGCCAGUGUUAUCGCAAGGACAUCUCCAACGGGUUCGCUCACACCCCAAUCAUCGAUCGGUGCGAAAUGCCAAUUGGGAACACGGACCGAAACACAUCGAUAGACUAAGUUCGGGAUUCCUUUGUGCUCGGCCCGUGCUGGUUGAACUCCAUCAAGUGCUCAGCACUGUGACACGGGAUUCGGGAGCGCAAUCGAGCGGGGGAGAAAUUUACGCAUGUGGUUCGCGCAACUAUGUUUUACAAGAGGCUAUGAGGCCCACUCAUGCUAUGCCUACGGUUCCCAUAGCUAAAACACCAUACGGAACGCUACGUCACCGGGCUAGAGGACCCAGCUUGAGCACAACUCAUAUAGAUUCACCCGUACCGCGCAAGUCACGAAGUAGGUCAAUCAUGCGGUGUCAGUCCUAUUCGACGCACCUCCUGCAGCCGACGGUCAACCGCAUGCUGGAAAGCUAUUCCGCAAACGUAAACACUUGUUUCUUUUCGGCAAACCGUAUAAGUCGCCUGCCCAUUGAAGACUCUAAUCUAAACAGUUCAAUUGAGAUACAUCGGCGGGCAUGCACCAGGAAUCUAUUGAACAACCAUUCAAUAAGGGAAGUAUGCAACGAGCUAGAUUGGGCCGCGGCGCAGAGUAUCUCAUCUUAUAGUUCACCUACGCUUGUUAGGAAUCUGUGCAACGUUUACAGUACACAACAGGGAAAGUCCGACGAGAUAGGGGAGAGGCAGGUACGGUGUUCGUACAAGCCUUCGGUUCUGGUCAAUUUGUCUGUGCCUUGGAAAUACAUCAGGCGGUCGAUAGACCGACCCCUAAAGUGCCCGUGCAGGCUGCUUCUUCAAGGCUCGUGUGGAACGAAAUUACCUUCUUUAUAUCUUGUUACGGUAGCCUUCUCAGGGCAACAUGGCGGCAUUGCCUCUGGCCGAUUAGUGCGCAGCCGCGAAGGGUGUUUAGUACAUCAAUACGGGGGUGAUACCCGAAAUUCCUUAUAUGCAAAUGAAGCGGGUGCGAGUGGGCUAAGUUCAUACCGAACUGUGGGAGGCGCGAUUGCUCUGCACCCCGCAAAAGUGAUCCUCCAUGGUCUCCAUGCGAACCUUACUUUACUGGGAAUGGUCCGACGGUUAGCUUAUACAUAUAACUUGGCAGGGAGGAAGAUGCUUCAUUAUGUUAUUGCGUAUAAUUGUAGAUUGAGACACGCGGUAAUAGUACAUCAGAGCCGUCGAGACCUCUGUCCCUCCAGACUCGUACCAGGGUCUCUAUUUCAUUUACAAGAUGUGUUAGGGGUGACAUGGGGGAACGUAUCAGAGACUCCUAGUUGGUACAGGAGCGAAUAUCAGCCAGCAUUCCUAACGACGGGUACGCUUAAUGCGCCACGCUUCUGCAAGGGUAAGCUCAAACUACAGGACUUGAAACAUCCCCAUUAUCAGUGUAUCCGCCAUUCCUUCAGACAGACAUUAUCCGUGUACCGACCCGGUCCGAGUAUCGGCAUAGCGUUAAAUCGAGUAAAACUUUUAGAGAUGAAUUGUGUACCCGAGAUGCGCUAUGUCUACAGGAAAAAGAGCAGUGCAAUUCCAAUUGUGUCAGGUUUGUUAGUGCGUACGGAGAAUUUAGCCAUUACAAUGCGGGGCCGAUCGUAUGGGCAGGGCUGCCAUUCAUUUACGCAAACUAUAUUGCGGCAUGAAAUGGGAAUUUUCUCGCUGCCCGCGGCCGCCGCUCCCUACGUUCAAGUGACUCGAUCCGGUUCUCCGUCGUCCAACGUGCUAGAAACAGUUGAGUCGAAUCGAUUCCGUAACAAACGCGUGGUGUUUUACCAUACAUCCACGCAGAGCCGUGUCGCCCUUCGGUUGCUAGCCGCCUCGUCAAUUCAGGGCUCGACGACACGGCAGCCUACGCAAGAAUUCACGCAGCCAAGUAGUGUUACUUGGGUCUGGAGUUACCGCAUACCUGAAGACGCAUCGGCUAUCACCUUCUCCAUCGUGUCUGUGUCGGAAUGGUGCUUUAACACCAAACUGGAAAGAUACUGCAAUUGGGUGAUAUGUCCAUUGCAUUUGUUCAGCGCCAUCCCCACGUUAAUGGCGAGCCAAGAAGAACAUCGACCGCCUGCUUCCGACUGCGCGAGGAUGGUAGCCCCUCGUUACGCACCAUUCUACCCAGAUUGUAGCGAAGUUUGGCCGGUGUGGCCACUCCAUAUGAGUGUCGGGGAAGUGAGUAGAAAGCGCCCUUUCGACAGUGUGACUAAAGCGUGUUGUGAAACUCCCGCGCGUAAGCUGUCUGAGUAUUCAGCACGUACGGGCUUCGUGUCAAUGCUGGACGCAACAAGAAGAGGAUAUGUCUGUUCAAUGUCGGACAUUGAGGACUACCCUGUAGAUUUGGUCCAGGUCUCCGAUCGGUGUUUCUGGGUCAACUUACUAUCUCUCCCGUAUCACGCCAGGUGGGCUAUUUCACGGCAACCCUCCAUUGCGCUAUUAAGUCGCCCCAUGCGGAUGUUAGUUAACAGAGGCACAUUGGUCCUUACUACCGCGACAAUACGGUCGGAAGCACCAUUUUUUGAAAGCCGUUCCUCAGGAGUGUCGAUUACGUGUGUCAAGUCCUUAGUAUCUAUCGAAGUCGACUUACUUGUGCCGCCCUGCCUGAGAUGUCGCCUAAGUAAAGGCAGGCAUCGCAGCCACACCGUUAUAGCAUUGGUACUGCAAUACCUCAUCCUUAAGAUACACAUUCUUGGAGUAGGCGGCUUUACUGGGCGAACUCUACACCAUACAUUUAGAACAGACUCAUGGGCAUACGUAUGGUGUCCAAAUCCCAUCAUUUUACUUUUGGUUGACUGCUCUCUAGAACGUUCGUCCGCAAACUACUCGCUGACAUCAAGGGCUUGGACGCGGCAAAAAGGGACUAUAGGCAUUAUCCAUUACGGGACUGACAGAAAUGGCCCUCCAGAGAUCAGCCCUGUACUGAUCGCUACUUUUAAAGCUACCUUCAGGAGUCCAUUAAAGCUUACGUUCCACUACUCCAAAGUACGUGUUCCCCCUGAUAGUGCUAUAGACAGGGAGUCAGCAUACCUCGGGUCCUUGGUUCACCUACGCAAAAAUCGAGGGGCUCUUGCGGGCUCUCGCAUGUACCGCAACAUUGGCCAACUAACUGCCCCCUUGCCAGGCCUAACACACAAUCUCAUUUUCCACACCUACACCGAUGAAGCUUCCGUGCAAAACUGGACGCGGCCCUUCUCCCUAGAUAAAAUCGCGGCGGGCGUAGCGUCACUAGCCCCUAGAGGAGUCGGGCACAGGCCGGUCUUCGCUAUUACUCGUAGGGUACUAAGGGGGGGCGGACGGAAUUCUGGUCGCUCUAUGGCUCACAUUAGGCAUACACCCACCAUAGGCUGCAGCCAGGUUCAAAUUCUCUCUUUGACCACGAUAAUUAUCUGCCGAAGGCUUUCUGACCAGGCGCCACCGUUGGGGAAAAGGUCUCAUCGCCUGCGGGCUCUCGGCAACAACGUCCUACCAGGCAGUUGGCGUUAUGAUCAACGAAAUGAAACGACUGGGUGUUUUUUUCGGAUGAGGUGGAUGAAAGGAACGGCAGUAGCCCCUAACCCCCCUCAUGACAAGAUAUCAUCUAAUCUCAACACGAUCCCUGUGGCAAGCAGUGAGUCGCCCUUUCCGAGGUUAGAAAGUCUACCCGGAUUAUAUCCGCGCCCAGGAAGGAGCGUCAUACAUGCUGCAAAUGCUGCUACAGCGAGAACAGUGUGUUGUUACCAAGUCGUGAGAGGCUCAUCUCACCGUAGGCGUACUGAAUUCUUCGAGGUGCGUUUAGACGGUGAUCGAGGCGCCCAAGUCCUUGGGACACGAAAAGCCGUAUCGAGCGCAACGAAUUCGGGCAGGUUAUACACUCAGCUUACAUUUGUAGUCAUAUAUCGGCUGGUAACUGCGGCGCCUACAUUCAAGUCUUCACCGAAAGCCUAUUGCCAAACCGCCGACGAAGACAACUCGUCUGGUAUAUGUGUCAUAGAAGCAGUACUGAAGCUGCUUCCUGCUACGAUGCCCACUAAGCCCUUCGCCACGUGGGCCUCACUACACAUAAGAGCGCCGCGACAUGGAAGCGUUGGACAAUAUUGGAUACUCGGUCCAAGCGGUGGAAAGAUUACUUCUUCACCGCUCUCGAAGCACCGGCAGAACGGGAGUUCUGGGACCAAAUCGUCGAUUGCCGACGAAAUAUUAGGCUUGUUGGCGUUCAGUACAUCUCCCACUAUUACUAUGCGACAAGGGCCUACUGCCGCGAUUUUCACCAAUGGCAACGGGGUAAUGCCCCGGCGCUGGACACAAUGGCGUAGCCCUUACGCUAUACCCCGCGCACCCUCGGCAGGUCACUACCCAACUGUUGUGUCAAGUAAAAAGAUCGGGUGGAUGUCCAACACCAGUCGAAUGGCUUCAAAGGAUGGUCUCCUGCUACGCCUUGUGAAGGUUCCCGAACGCUUUAAGCGGAGCAUACAGGGGCCCGAAAGUUCCUGGCCCAAGUUUGCACGGUACGCGUAUGCGCCUAUACCUCAAACGUAUUUUUCUUUGCCGCAGCGGUAUUGCAUACAUCGUUUCGGUUUAUUUAGCACGCUCCCUCGUAAGCUUUAUCGAGGUCACGAGAAAAAUCUCUGGAAUUUGCAGCCAUGUGGUUACCACACCACUCUGCGAAGAACCUCGGCCGACGCACGGGCAUCACGCAUAGUUGGUACUUCGGAGGAGUGGGUCAGAGAGCUAGGGCCAGGUGAGGCGAGCAGCAUCGCGGGGAGUGGUGCUUCUCUGAGCAGUUGUUCUUCGAGUGUCUUCAGGGGGCAGCGUGAGAGGCUAUCACACAUUACAAAUUCGUCCAUGCUCCGCUCUUAUCUGUCGCCACUGUACUGUCAGGUACCUUAG'

print(rna_to_protein(rna))